### PR TITLE
PD-195: Badge

### PR DESCRIPTION
**Pull request by fredtruman**
Screenshot 2019-03-28 13 57 01

@DesignerDave

### CODE REVIEW

**Comment by fredtruman** [comment]
I center-aligned the text ... so there, @chrissygonzalez 

Screenshot 2019-03-28 17 06 02

**Comment by dhastwell** [comment]
When I was looking at the modify string checkboxes for filtering, I discovered white text on yellow doesn't pass contrast ratio legibility. Atlassian use brown text on yellow for their 'In-progress' label. 

I have my example here in the filtering designs: https://mongodb.invisionapp.com/share/FKPEOGO2YTE#/352433898_All

Side note: The modify, confirm change not actually being built for other reasons, but thought I'd share my treatment for text on yellow background.

**Comment by fredtruman** [comment]
Ah... yeah good catch @dhastwell . Let me kick some ideas here for additional feedback.

**Comment by DesignerDave** [comment]
The symbols functionally look good. Echoing Dave, the contrast issue is real with the yellow badge though.

**Comment by fredtruman** [comment]
Some (possibly overkill) thoughts @DesignerDave and @dhastwell

Screenshot 2019-03-29 11 55 22
Screenshot 2019-03-29 11 55 27
Screenshot 2019-03-29 11 55 35

**Comment by fredtruman** [comment]
Actually, ignoring those previous comments as I think they can be considered as part of the Banner library. For now, I've bumped contrast for:
- Warning text
- Default text
- Outline text

Screenshot 2019-03-29 13 52 51

Will file tickets and coordinate with @brookescarlett if this LGTY @DesignerDave

**Comment by DesignerDave** [comment]
Much improved! 👍

**Comment by dhastwell** [comment]
A little late to the party...

These are nice. :)

**Pull request merged**
