### PR TITLE
Breadcrumb Component

### PR DESCRIPTION
**Pull request by ingridh**
**Old:**
screen shot 2018-09-25 at 9 02 38 am

**New:**
screen shot 2018-09-25 at 9 02 48 am

1. Completed step should be green with green check mark next to it
2. Current step should be bold with no check mark
3. Subsequent steps should be in gray text

**note**: both the text and the font awesome check mark should be 14px

### CODE REVIEW

**Comment by ingridh** [comment]
This is what it currently looks like bolded for the subsequent steps. I think it's also like this currently on dev (see create alert on org level). 

screen shot 2018-09-25 at 1 00 59 pm


There is still going to be a slight shift for the checkmark. So this is what it looks like if we left space. It's slightly lopsided which I don't think looks as good:

screen shot 2018-09-25 at 3 38 15 pm


What do you guys think? 🤔

**Comment by elianekabkab** [comment]
what if we bold the text on both? the difference would be gray/black text?

If we do leave room for the checkbox (I think we probably should), what if we left room on either end?

**Comment by fredtruman** [comment]
Agree with that @elianekabkab - we could probably tighten up the space on the left side between the green checkmark and the edge of the step container, and then make the right side padding *visually match (i.e. since there is that angled arrow it doesn't need to be quite as much, but just enough to visually balance)

I think it's fine if the only difference for active vs. future steps is the color of the text, though if we wanted to add a second parameter for differentiation we could slightly gray out the background of the future step? 🤔

**Comment by ingridh** [comment]
So @elianekabkab the screenshot above has both bolded. Here is what it looks like if we left more room on both sides. I think it definitely looks better.

screen shot 2018-09-25 at 5 17 28 pm

**Comment by fredtruman** [comment]
Overall I think that LGTM @ingridh :shipit: 

**Nitpick:** Could probably tighten padding on left/right a bit - the checkmark might not need as much padding on its left side as the text does on its right, so the states without checkmarks don't have so much empty whitespace on the left.

**Comment by ingridh** [comment]
**Updated with** 
- Breadcrumb symbols! (this is in sketch file)
- Preview of breadcrumb (this is in sketch file)

screen shot 2018-10-10 at 11 39 47 pm
screen shot 2018-10-10 at 11 41 55 pm


- Instructions on how to use the symbols! This will be in a separate sketch files available in our shared drive folder in case of confusion.

screen shot 2018-10-10 at 11 39 52 pm

**Comment by fredtruman** [comment]
Looks awesome @ingridh ! 👏 
The only nitpick (if you're up for it): I think it would make more sense to left-align the text and checkmark so that if you add different (longer/shorter) text it will maintain consistent spacing on the left. The designer can just adjust for right side padding rather than trying to manage padding from both sides. What it does now if I increase size:

screenshot 2018-10-11 09 59 33

Otherwise merge away if you'd like :shipit:

**Comment by ingridh** [comment]
Left aligned!

@elianekabkab do you want to sign off before I merge?

**Comment by fredtruman** [comment]
@ingridh was also thinking to tether the text box as well as the checkmark in position relative to the left hand side of the parent container, like so:

screenshot 2018-10-12 10 48 33

😬

**Comment by fredtruman** [comment]
ty! 🚢 Let's shipit @ingridh looks great! 👏

**Pull request merged**
