### PR TITLE
[PD-163] Add dark-mode toggles

### PR DESCRIPTION
**Pull request by DesignerDave**

### CODE REVIEW

**Comment by DesignerDave** [comment]
I just updated `Default` to `Static`. That was totally accidental, I also prefer `Static`.

In terms of naming in the Sketch libraries, I don't think it's necessary to map spelling 1:1 with what's in the React component library. I think `xSmall` for the property value in React and `Extra Small` in the symbol library is okay, as long as it translates nicely when communicating to developers what component to use. I think overall, we gain more by using human-readable names for the symbols. We should update any symbol names to use human-readable names.

**Comment by fredtruman** [comment]
Sounds good. So would your preference here be "Extra Small" vs. "X-Small" in symbol library menus?

**Comment by DesignerDave** [comment]
Sorry if that wasn't clear. We should prefer human-readable names. Here, I prefer "Extra Small".

**Comment by fredtruman** [comment]
SGTM, will create ticket to rename existing "X-Small" menu items!

**Comment by fredtruman** [comment]
:shipit: 👍

**Pull request merged**
