### PR TITLE
PD-91: Tooltips

### PR DESCRIPTION
**Pull request by fredtruman**
Moving to this PR to avoid rebase weirdness. See: from https://github.com/leafygreen/sketchUILibrary/pull/39 for previous work.

### CODE REVIEW

**Comment by fredtruman** [comment]
RFAL @DesignerDave 

screenshot 2019-02-28 10 49 37

**Comment by DesignerDave** [comment]
Can we fix the alignment of the arrow for non-centered orientations? Right now the arrow moves as you expand the tooltip.

screen shot 2019-02-28 at 10 55 29 am

**Comment by fredtruman** [comment]
Ah! Yep 👍 coming up

**Comment by fredtruman** [comment]
RFAL @DesignerDave

**Comment by DesignerDave** [comment]
LGTM!

**Pull request merged**
