### PR TITLE
PD-91: Tooltips Symbol Library

### PR DESCRIPTION
**Pull request by fredtruman**
@DesignerDave One size, 4 variants for:
- bottom
- top
- left
- right

screenshot 2019-01-30 17 01 31
screenshot 2019-01-30 16 57 07

One small change to the Button file to display cover graphic in mac OS Finder

### CODE REVIEW

**Comment by DesignerDave** [comment]
Do we not intend on supporting alignments other than center?

e.g.
```
 ____________
|    text    |
|__________ _|
           V
```

vs
```
 ____________
|    text    |
|_ __________|
  V
```

**Comment by fredtruman** [comment]
That ascii is amazing! But good question. Would it make the conditional logic more cumbersome? i.e. By default show with bottom arrow, if too close to the right edge use the right arrow version, but if the element is ... yadda yadda yadda?

I don't have strong opinions on why we shouldn't support those from a design point of view.

Actually wondering your thoughts as well on a couple other cases, should we include variations here that support `new lines` and/or limited html? I know we do a bunch of funny things in special cases for tooltips, for example (might not be valid uses of tooltips):

`new line` support:
screenshot 2019-01-30 17 21 11

`html link` support, also this example tooltip is invoked / toggled on click of the info icon (vs. strictly information displayed on hover):
screenshot 2019-01-30 17 21 23

**Comment by fredtruman** [comment]
Cool, thanks Dave! Would you advise, in addition to the 4 variants I've included (top, right, bottom, left), to include some variants for 4 more? (top-left, top-right, bottom-left, bottom-right)

Also, not sure what you think, but I'm iffy on the other 4 logically implied variants: `left-top`, `left-bottom`, `right-top`, `right-bottom`?
```
 ____________
|    text        |>
|                  |
|__________ _|
       
```
```
 ____________
<|    text        |
  |                  |
  |__________ _|
       
```
```
  ____________
  |    text        |
  |                  |
<|__________ _|
       
```
```
 ____________
|    text        |
|                  |
|__________ _|>
       
```

**Comment by DesignerDave** [comment]
I think we're fine with just the top and bottom alignments for the time being.

**Comment by fredtruman** [comment]
Moving to https://github.com/leafygreen/sketchUILibrary/pull/39 to avoid rebase weirdness

**Pull request closed without merging**
