### PR TITLE
Add radio input symbol

### PR DESCRIPTION
**Pull request by DesignerDave**

### CODE REVIEW

**Comment by DesignerDave** [comment]
My going convention for naming has been to name the symbol, not the context it's used in.

Toggle is default and dark, because the non-default symbol is darker. Whereas the checkbox and radio button are default / light because you use the lighter version on a dark background in those cases.

**Comment by fredtruman** [comment]
Ok that's cool. If we did name according to context could it guide towards prescriptive use, or is that confusing?

**Comment by fredtruman** [comment]
:shipit:

**Comment by DesignerDave** [comment]
Sorry – If we name according to context, I think we should do something like `On Light`, `On Dark`, etc. Right now, the naming is consistent with leafygreen-ui.

**Comment by fredtruman** [comment]
No worries! Was just saying :shipit: cuz I'm cool with that thinking if you are!

**Comment by DesignerDave** [comment]
SGTM!

**Pull request merged**
